### ISSUE TITLE
Duplicate resource names

### ISSUE THREAD

**Issue by colby** [copious-cookbooks/redis#10]
```
==> data:   Cloning resource attributes for mysql_database_user[craft] from prior resource
==> data: Previous mysql_database_user[craft]: /var/chef/cache/cookbooks/cop_mysql/recipes/tables_and_users.rb:20:in `block in from_file'
==> data: Current  mysql_database_user[craft]: /var/chef/cache/cookbooks/cop_mysql/recipes/tables_and_users.rb:27:in `block (2 levels) in from_file' at 1 location:
==> data:     - /var/chef/cache/cookbooks/cop_mysql/recipes/tables_and_users.rb:27:in `block (2 levels) in from_file'
```

**Comment by colby** [comment]
Wrong repo.
